# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dcb8646744399da770bd733155f77970ada8af6d7be57d644f24114d1e776e330b85313a051746490924649e7f0439fa787701faaa7b6957435d349b04bf79ff
  mail:
    password: gaesi2017
    user_name: gaesi.talents@gmail.com

test:
  secret_key_base: ddcdf0403ba836a823c33b70d3cfb77a2b2d5c7b32cd00af264e689e0c8365e28a9e3f8d1c9423deb9a3e50564f54daf9a13c286fc21eccecf9a2aab69af1b80
  mail:
    password: gaesi2017
    user_name: gaesi.talents@gmail.com

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  mail:
    password: gaesi2017
    user_name: gaesi.talents@gmail.com